/*
Notebook Navigator - Plugin for Obsidian
Copyright (c) 2025-2026 Johan Sanneblad

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

=========================================================================
GENERATED FILE - DO NOT EDIT src/constants/notebookNavigatorIcon.ts
=========================================================================

Edit the SVG source instead: icon.svg
Generated by: scripts/build-icons.mjs
*/

// Icon identifier used with Obsidian's addIcon()/setIcon()
export const NOTEBOOK_NAVIGATOR_ICON_ID = 'little-red-gallery';

// Inner SVG content passed to addIcon() (Obsidian wraps this in <svg viewBox="0 0 100 100">)
export const NOTEBOOK_NAVIGATOR_ICON_SVG = `<g stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
    <rect x="13" y="16" width="74" height="68" rx="14" stroke-width="7"/>
    <line x1="50" y1="22" x2="50" y2="78" stroke-width="5"/>
    <rect x="21" y="26" width="21" height="19" rx="5" stroke-width="4"/>
    <path d="M22 67L29 59L35 64L42 55" stroke-width="4"/>
    <circle cx="36" cy="31" r="2.5" fill="currentColor" stroke="none"/>
    <rect x="58" y="26" width="21" height="29" rx="5" stroke-width="4"/>
    <line x1="61" y1="61" x2="77" y2="61" stroke-width="4"/>
    <line x1="61" y1="69" x2="73" y2="69" stroke-width="4"/>
    <path d="M41 84L50 73L59 84" stroke-width="5"/>
  </g>`;
