/*
Notebook Navigator - Plugin for Obsidian
Copyright (c) 2025-2026 Johan Sanneblad

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

=========================================================================
GENERATED FILE - DO NOT EDIT src/constants/notebookNavigatorIcon.ts
=========================================================================

Edit the SVG source instead: icon.svg
Generated by: scripts/build-icons.mjs
*/

// Icon identifier used with Obsidian's addIcon()/setIcon()
export const NOTEBOOK_NAVIGATOR_ICON_ID = 'little-red-gallery';

// Inner SVG content passed to addIcon() (Obsidian wraps this in <svg viewBox="0 0 100 100">)
export const NOTEBOOK_NAVIGATOR_ICON_SVG = `<g stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
    <rect x="16" y="13" width="60" height="74" rx="13" stroke-width="7"/>
    <path d="M31 13V87" stroke-width="5"/>
    <path d="M42 32H62" stroke-width="5"/>
    <path d="M42 46H55" stroke-width="5"/>
    <rect x="42" y="58" width="22" height="16" rx="4" stroke-width="5"/>
    <path d="M45 71L51 65L55 69L61 62" stroke-width="4"/>
    <path d="M73 34L84 45L73 56" stroke-width="7"/>
    <path d="M68 45H84" stroke-width="7"/>
  </g>`;
